version: "2"

checks:
  argument-count:
    config:
      threshold: 5 #Allow at most 5 arguments in a function
  method-count:
    config:
      threshold: 25 #Allow at most 25 functions in a class

exclude_patterns:
  - "frontend/"
  - "backend/*/*/migrations/*"
  - "backend/config/**"
