version: "3.8"

services:
  backend:
    container_name: app-backend
    restart: always
    build:
        context: .
        dockerfile: ./backend/docker/django/Dockerfile
        args:
          - APP_ENV=dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/opt/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY-REPLACE_ME}
      DEBUG: ${DEBUG-TRUE}
      DATABASE_URL: ${DATABASE_URL-postgres://app_dev:OwOtBdfep9Frut@db:5432/app_dev}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS-127.0.0.1,localhost}
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  db:
    image: postgres:14.4-alpine
    container_name: app-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB-app_dev}
      POSTGRES_USER: ${POSTGRES_USER-app_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBdfep9Frut}

volumes:
  postgres_data:
