# Generated by Django 3.2.14 on 2022-09-20 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('measurement_unit', models.CharField(help_text='For example, a kilogram', max_length=200, verbose_name='Measurement unit')),
            ],
            options={
                'verbose_name': 'Measurement unit',
                'verbose_name_plural': 'Measurement units',
            },
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='recipes_ingredient_name_measurement_unit_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__len__gt', 0)), name='recipes_ingredient_name_is_empty'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('measurement_unit__len__gt', 0)), name='recipes_ingredient_measurement_unit_is_empty'),
        ),
    ]
