# Generated by Django 3.2.14 on 2022-10-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_recipe_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
