# Generated by Django 3.2.14 on 2022-10-05 05:35

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_customuser_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follow_by',
            field=models.ManyToManyField(
                blank=True,
                related_name='his_following',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Who I follow',
            ),
        ),
    ]
