# Generated by Django 3.2.14 on 2022-10-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_follow_by_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='follow_by',
            new_name='followers',
        ),
    ]
