# Generated by Django 3.2.14 on 2022-09-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_add_tag_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
